#!/usr/bin/env bash
# Build pipeline for SecureVault-RE. Reproducible, single entry point.
# Order (must not be changed, see CLAUDE.md #8):
#   1. mvn compile
#   2. obfuscate the protected packages (keyparts, crypto, vault)
#   3. bootstrap-encrypt the obfuscated classes -> resources/vault/*.bin
#   4. generate the deterministic integrity anchor (vault/integrity.anchor)
#   5. generate flag.enc from the real key-derivation chain (hashes that
#      same anchor file for KeyFragmentGamma)
#   6. mvn package (bundles the same anchor file into the final jar)
#   7. scripts/smoke-test.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PROTECTED_PACKAGES=(keyparts crypto vault)
FLAG_TEXT="${SECUREVAULT_FLAG_TEXT:-FLAG{ecb_leaks_repeated_blocks_and_reflection_hides_the_key}}"

echo "== [1/7] mvn compile =="
mvn -q -f pom.xml compile

echo "== [1b] building helper tools (obfuscator, buildutil) =="
mvn -q -f tools/obfuscator/pom.xml package
mvn -q -f tools/buildutil/pom.xml package

echo "== [2/7] obfuscating protected packages =="
rm -rf target/protected-classes target/obfuscated target/obfuscation
mkdir -p target/protected-classes/de/dhbw/securevault
for pkg in "${PROTECTED_PACKAGES[@]}"; do
  cp -r "target/classes/de/dhbw/securevault/$pkg" "target/protected-classes/de/dhbw/securevault/"
done

java -jar tools/obfuscator/target/obfuscator.jar \
  target/protected-classes \
  target/obfuscated \
  target/obfuscation/rename-map.properties
# rename-map.properties is a build-internal debug artifact only (kept under
# target/, never shipped): NameRegistry.java is regenerated by the
# obfuscator itself with the real names baked in as literal string returns,
# then obfuscated+encrypted like every other protected class -- no
# name-registry properties resource is packaged into the final jar.
cat target/obfuscation/rename-map.properties

echo "== [3/7] bootstrap-encrypting obfuscated classes -> resources/vault/*.bin =="
rm -rf resources/vault
mkdir -p resources/vault
java -jar tools/buildutil/target/buildutil.jar encrypt-classes target/obfuscated resources/vault

echo "== [4/7] generating deterministic integrity anchor =="
java -jar tools/buildutil/target/buildutil.jar generate-anchor resources/vault/integrity.anchor

echo "== [5/7] generating flag.enc =="
java -jar tools/buildutil/target/buildutil.jar generate-flag resources/vault/integrity.anchor "$FLAG_TEXT" resources/flag.enc

echo "== [6/7] mvn package =="
# Wire the staged resources (vault/*.bin incl. integrity.anchor, flag.enc)
# into the classpath by copying them into target/classes before packaging.
# The protected packages' plaintext .class files are excluded from the jar
# via pom.xml's maven-jar-plugin <excludes> (see CLAUDE.md's "muss klar
# trennbar sein" requirement) -- necessary because `mvn package` re-runs
# `compile` and would otherwise re-populate target/classes with them.
cp -r resources/vault target/classes/
cp resources/flag.enc target/classes/
mvn -q -f pom.xml package

echo "== [7/7] smoke test =="
"$ROOT_DIR/scripts/smoke-test.sh"

echo "== build complete: target/Anwendung.jar =="
